version: '3.8'

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dockerbridge.local:
        ipv4_address: 192.168.123.101

  app:
    container_name: baseline-monitoring-app
    hostname: local.baseline-monitoring.de
    build:
      context: ./config/docker
      dockerfile: Dockerfile
    volumes:
      - .:/home/baselinemonitoringdev/current
    ports:
      - "82:80"
    labels:
      - "traefik.http.routers.baseline-monitoring-app.rule=Host(`local.baseline-monitoring.de`)"
      - "traefik.http.services.baseline-monitoring-app.loadbalancer.server.port=80"
    networks:
      dockerbridge.local:

  database:
    container_name: baseline-monitoring-db
    hostname: localdb.baseline-monitoring.de
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: baselinemonitoring
      MYSQL_USER: baselinemonitoring
      MYSQL_PASSWORD: baselinemonitoring
    ports:
      - '3307:3307'
    volumes:
      - ./config/docker/mysql:/var/lib/mysql
    networks:
      dockerbridge.local:
        aliases:
          - localdb.baseline-monitoring.de
    labels:
      - "traefik.http.routers.baseline-monitoring-db.rule=Host(`localdb.baseline-monitoring.de`)"
      - "traefik.http.services.baseline-monitoring-db.loadbalancer.server.port=3307"

networks:
  dockerbridge.local:
    name: baseline_dev_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.123.0/24
