version: '3.8'

services:
  database:
    container_name: baseline-monitoring-db
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: baselinemonitoring
      MYSQL_USER: baselinemonitoring
      MYSQL_PASSWORD: baselinemonitoring
    ports:
      - '4306:3306'
    volumes:
      - ./config/docker/mysql:/var/lib/mysql
  
  php:
    container_name: php
    build:
      context: ./config/docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/baseline-monitoring
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/baseline-monitoring
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
